accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/follow', views.follow, name='follow'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('reviews.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/like/', views.like, name="like"),
    path('<int:pk>/comments/', views.comment_create, name="comment_create"),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name="comment_delete"),
]

accounts/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name = 'followers')

reviews/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(upload_to="images/", blank=True, null=True, processors=[ResizeToFill(400, 300)],
    format = 'JPEG', options={'quality':80})
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'like_reviews')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)

class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    review = models.ForeignKey(Review,on_delete = models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model  = get_user_model()
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email',)

reviews/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

accounts/views.py
from django.contrib import messages
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model

from reviews.models import Review , Comment
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from .models import User

# Create your views here.

def index(request):
    users = get_user_model().objects.all()
    context = {
        'users':users,
    }
    return render(request, 'accounts/index.html', context)

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm (request.POST, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('accounts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    reviews = Review.objects.filter(user_id=pk)
    comments = Comment.objects.filter(user_id=pk)
    context = {
        'user':user,
        'reviews':reviews,
        'comments':comments
    }
    return render(request, 'accounts/detail.html', context)


@login_required
def follow(request, pk):
    user = get_object_or_404(get_user_model(),pk=pk)
    if request.user == user:
        messages.warning(request, '스스로를 팔로우 할 수 없습니다.')
        return redirect('accounts:detail', pk)
    if request.user in user.followers.all():
        user.followers.remove(request.user)
    else:
        user.followers.add(request.user)
    return redirect('accounts:detail', pk)

reviews/views.py
from django.shortcuts import render, redirect
from reviews.forms import CommentForm, ReviewForm
from reviews.models import Review, Comment
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
def index(request):
    reviews = Review.objects.all()
    context = {
        'reviews':reviews,
    }
    return render(request, 'reviews/index.html', context)

def create(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user 
            review.save()
            return redirect('reviews:index')
    else:
        review_form = ReviewForm()
    context = {
        'review_form' : review_form,
    }
    return render(request,'reviews/form.html', context)

def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.user == review.user: 
        if request.method == 'POST':
            review_form = ReviewForm(request.POST, request.FILES, instance=review)
            if review_form.is_valid():
                review_form.save()
                messages.success(request, '글이 수정되었습니다.')
                return redirect('reviews:detail', review.pk)
        else:
            review_form = ReviewForm(instance=review)
        context = {
            'review_form': review_form
        }
        return render(request, 'reviews/form.html', context)
    else:
        messages.warning(request, '작성자만 수정할 수 있습니다.')
        return redirect('reviews:detail', review.pk)

def delete(request, pk):
    review = Review.objects.get(pk=pk)
    review.delete()
    return redirect('reviews:index')


def detail(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm()
    context = {
        'review' : review,
        'comments': review.comment_set.all(),
        'comment_form' : comment_form,
    }
    return render(request, 'reviews/detail.html', context)

@login_required
def like(request ,pk):
    review = Review.objects.get(pk=pk)
    if request.user in review.like_users.all() :
        review.like_users.remove(request.user)
    else:
        review.like_users.add(request.user)
    return redirect('reviews:detail', pk)

@login_required
def comment_create(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
    return redirect('reviews:detail', review.pk)


def comment_delete(request, pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('reviews:detail', pk)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>회원 정보페이지</h1>



<p>이름 : {{ user.username }} </p>
<p>최근 접속시간 : {{ user.last_login }}</p>
<p>이메일 : {{ user.email }}</p>
<p>팔로우:
  {{ user.followings.count }}
  팔로워:
  {{ user.followers.count }}
</p>


{% for review in reviews %}
<p>제목 : <a href="{% url 'reviews:detail' review.pk %}">
    {{review.title}}</p>
</a>
</p>작성시간 : {{review.created_at}}</p>
<br>
{% endfor %}

{% for comment in comments %}
<p>댓글 : <a href="{% url 'reviews:detail' comment.review_id %}"> {{comment.content}}</a></p>
<p> 작성시간 : {{comment.created_at}}</p>
{% endfor %}

{% if request.user != user %}
<a href="{% url 'accounts:follow' user.pk %}">
  {% if request.user in user.followers.all %}
  <button class="btn btn-outline-danger mb-3">팔로우 취소</button>
  {% else %}
  <button class="btn btn-outline-success mb-3">
    팔로우</button>
  {% endif %}
</a>
{% endif %}

{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>회원 목록</h1>

<table class="table m-5">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">회원 이름</th>
            <th scope="col">email</th>
            <th scope="col">최근 접속 시간</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for user in users %}
            <th scope="row">{{ user.id}}</th>
            <td><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></td>
            <td>{{ user.email }}</td>
            <td>{{ user.last_login }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>로그인</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>회원가입</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>

{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

<h1>{{ review.title }}</h1>
<h4 class='d-flex justify-content-end'>
  <a class='mx-3' href="{% url 'accounts:index'%}">{{ review.user.username }} </a>
</h4>
<h4 class='d-flex justify-content-end'>작성시간 : {{ review.created_at|date:"SHORT_DATETIME_FORMAT" }} </h4>

<span>
  {% if request.user.is_authenticated %}
  <a href="{% url 'reviews:like' review.pk %}" style="color: red; text-decoration: none !important">
    {% if request.user in review.like_users.all %}
    <i class="bi bi-heart-fill">좋아요 취소</i>
    {% else %}
    <i class="bi bi-heart">좋아요</i>
    {% endif %}
  </a> {{ review.like_users.count}}</span>
{% endif %}

<div class='my-4' style="height:auto; width: 800px; ">
  <p style="word-break: break-all;">{{ review.content }}</p>
</div>

{% if review.image %}
<img src="{{ review.image.url }}" alt="{{ review.image }}" width="400" height="300" />
{% endif %}
{% if request.user == review.user %}
<div>
  <a class="btn btn-outline-success mx-2" href="{% url 'reviews:update' review.pk %}">수정하기</a>
  <a class=" btn btn-outline-danger mx-2" href="{% url 'reviews:delete' review.pk %}">삭제하기</a>
</div>
{% endif %}
<h4 class="my-3">댓글</h4>
{% if request.user.is_authenticated %}
<form action="{% url 'reviews:comment_create' review.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form comment_form layout='inline'%}
  <!-- -->
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endif %}
<hr />
{% for comment in comments %}
<p>{{ comment.user.username }}
  |
  {{ comment.content }}</p>
<a class=" btn btn-outline-danger mx-2" href="{% url 'reviews:comment_delete' review.pk comment.pk %}">삭제하기</a>
<hr />
{% empty %}
<p>댓글이 없어요 ㅠ_ㅠ</p>
{% endfor %}
{% endblock content %}

reviews/templates/reviews/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>리뷰 작성 페이지</h1>
{% if request.resolver_match.url_name == 'create' %}
<br>
<h2> 글쓰기 </h2>
{% else %}
<h1> 수정하기 </h1>
{% endif %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form review_form %}
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock content %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>리뷰목록</h1>
<div class="d-flex flex-wrap">
{% if reviews %}
{% for review in reviews %}
<div class="card shadow m-3 relative" style="width: 20%;">
    {% if review.image %}
    <img src="{{ review.image.url }}" class="card-img-top" alt="...">
    <img src="https://an2-img.amz.wtchn.net/image/v1/updatable_images/2571/original/42e70f1bc34d7af54478a311983ecf6d3601eefa.png" alt="" style="width:16%;border-radius: 50%;position:absolute;background-color: white;padding: 0.3rem;right: 0;">
    {% endif %}    
        <div class="card-body">
            <p class="card-text"><a href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a>
                <br>
                {{ review.user.username }}
                <br>
                {{ review.created_at }}
            </p>
        </div>
</div>
{% endfor %}
</div>
<!-- <table class="table m-5">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">리뷰 제목</th>
            <th scope="col">내용</th>
            <th scope="col">작성자</th>
            <th scope="col">작성 시간</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for review in reviews %}
            <th scope="row">{{review.id}}</th>
            <td><a href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a></td>
            <td>{{review.content}}</td>
            <td><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></td>
            <td>{{review.created_at}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table> -->
{% else %}
<p>리뷰가 없습니다 ㅠㅠ</p>
{% endif %}
{% endblock content %}

templates/base.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <style>
    html,
    body {
      height: 100%;
    }

    .container {
      min-height: 100%;
    }

    .card:hover {
      transform: scale(1.15);
      transition: all 200ms ease-in;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-light px-5 mb-3">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'accounts:index' %}">
        <img src="https://cdn-icons-png.flaticon.com/512/1946/1946488.png" alt="img" style="height: 50px;"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'reviews:create' %}">리뷰작성</a>
            {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'reviews:index' %}">리뷰목록</a>
          </li>


        </ul>

      </div>
    </div>

    <ul class="navbar-nav  mx-2" style="width:40rem; ">
      <form class="d-flex pt-3" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success " type="submit">Search</button>
      </form>
      {% if request.user.is_authenticated %}

      <li class="nav-item mt-3 ">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
      <li class="nav-item mt-3 ">
        <a href="{% url 'accounts:detail' user.pk %}">
          <span class="nav-link">{{ user.username }}</span>
        </a>
      </li>
      {% else %}
      <li class="nav-item mt-3 mx-2">
        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
      </li>
      <li class="nav-item mt-3 ">
        <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">회원가입</a>
      </li>

      {% endif %}

    </ul>
  </nav>
  <div class="container" style="padding-bottom: 10rem;">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}{% endblock content %}
  </div>
  <footer class=" bg-dark" style="width:100%;height:4rem; ">
    <p class="fw-bold text-center text-white bi-align-middle" style="line-height: 4rem"> © created by <a
        href="https://github.com/mgpo-98" target="_blank" style="color:white;">조승윤</a>, <a
        href="https://github.com/hae-on" target="_blank" style="color:white;">백솔비</a>, <a
        href="https://github.com/wnsn8546" target="_blank" style="color:white;">최준우</a> at 10.28.2022</p>
  </footer>
</body>

</html>